/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRoadmapRouteImport } from './routes/_app/roadmap'
import { Route as AppResumeRouteImport } from './routes/_app/resume'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPlacementsRouteImport } from './routes/_app/placements'
import { Route as AppInterviewRouteImport } from './routes/_app/interview'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCommunityRouteImport } from './routes/_app/community'
import { Route as AppCareerGoalRouteImport } from './routes/_app/career-goal'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoadmapRoute = AppRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AppRoute,
} as any)
const AppResumeRoute = AppResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPlacementsRoute = AppPlacementsRouteImport.update({
  id: '/placements',
  path: '/placements',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewRoute = AppInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppCareerGoalRoute = AppCareerGoalRouteImport.update({
  id: '/career-goal',
  path: '/career-goal',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/career-goal': typeof AppCareerGoalRoute
  '/community': typeof AppCommunityRoute
  '/dashboard': typeof AppDashboardRoute
  '/interview': typeof AppInterviewRoute
  '/placements': typeof AppPlacementsRoute
  '/profile': typeof AppProfileRoute
  '/resume': typeof AppResumeRoute
  '/roadmap': typeof AppRoadmapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/career-goal': typeof AppCareerGoalRoute
  '/community': typeof AppCommunityRoute
  '/dashboard': typeof AppDashboardRoute
  '/interview': typeof AppInterviewRoute
  '/placements': typeof AppPlacementsRoute
  '/profile': typeof AppProfileRoute
  '/resume': typeof AppResumeRoute
  '/roadmap': typeof AppRoadmapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/career-goal': typeof AppCareerGoalRoute
  '/_app/community': typeof AppCommunityRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/interview': typeof AppInterviewRoute
  '/_app/placements': typeof AppPlacementsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/resume': typeof AppResumeRoute
  '/_app/roadmap': typeof AppRoadmapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/career-goal'
    | '/community'
    | '/dashboard'
    | '/interview'
    | '/placements'
    | '/profile'
    | '/resume'
    | '/roadmap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/career-goal'
    | '/community'
    | '/dashboard'
    | '/interview'
    | '/placements'
    | '/profile'
    | '/resume'
    | '/roadmap'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/career-goal'
    | '/_app/community'
    | '/_app/dashboard'
    | '/_app/interview'
    | '/_app/placements'
    | '/_app/profile'
    | '/_app/resume'
    | '/_app/roadmap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/roadmap': {
      id: '/_app/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AppRoadmapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resume': {
      id: '/_app/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof AppResumeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/placements': {
      id: '/_app/placements'
      path: '/placements'
      fullPath: '/placements'
      preLoaderRoute: typeof AppPlacementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interview': {
      id: '/_app/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof AppInterviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community': {
      id: '/_app/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/career-goal': {
      id: '/_app/career-goal'
      path: '/career-goal'
      fullPath: '/career-goal'
      preLoaderRoute: typeof AppCareerGoalRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCareerGoalRoute: typeof AppCareerGoalRoute
  AppCommunityRoute: typeof AppCommunityRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInterviewRoute: typeof AppInterviewRoute
  AppPlacementsRoute: typeof AppPlacementsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppResumeRoute: typeof AppResumeRoute
  AppRoadmapRoute: typeof AppRoadmapRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCareerGoalRoute: AppCareerGoalRoute,
  AppCommunityRoute: AppCommunityRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInterviewRoute: AppInterviewRoute,
  AppPlacementsRoute: AppPlacementsRoute,
  AppProfileRoute: AppProfileRoute,
  AppResumeRoute: AppResumeRoute,
  AppRoadmapRoute: AppRoadmapRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
